name: setup_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  easy_localization: ^3.0.3
  connectivity: ^3.0.6
  settings_ui: ^2.0.0
  auto_size_text: ^3.0.0
  rxdart: ^0.27.0
  flutter_rating_bar: ^4.0.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  http: ^1.1.0
  flutter_svg: ^2.0.10+1
  like_button: ^2.0.5
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  logger: ^1.0.1
  dartz: ^0.10.1
  excel: ^4.0.2
  pdf: ^3.8.4
  injectable: ^2.3.2
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.1.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  #  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  readmore: ^2.2.0
 # phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3
  # firebase_core: ^2.24.2
  #  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  firebase_messaging: ^14.0.0
  flutter_app_badger: ^1.5.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  sidebar_bigeagle: ^0.2.2+1
  location: ^5.0.3
  geolocator: ^9.0.0
  google_maps_flutter: ^2.2.0
  permission_handler: ^11.0.1
  intl: ^0.18.0
  connectivity_plus: ^3.0.3
  open_file: ^3.3.2
  app_settings: ^5.1.1
  package_info_plus: ^4.2.0
  flutter_phoenix: ^1.1.1
  file_picker: ^7.0.2
  flutter_secure_storage: ^9.2.2
  hexcolor: ^3.0.1
  flutter_platform_widgets: ^3.3.5
dev_dependencies:
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/
#    - assets/images/catalogue/
#    - assets/images/products/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
#        - asset: assets/fonts/Montserrat-SemiBold.ttf
#          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 900
